# Generated by Django 4.1.7 on 2023-03-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='formula',
            field=models.CharField(max_length=500),
        ),
    ]
