# Generated by Django 4.1.7 on 2023-03-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0006_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
