# Generated by Django 4.1.7 on 2023-03-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0007_recordatorio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
        ),
    ]
